version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/chatbot_db
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    volumes:
      - db_data:/var/lib/postgresql/data

  discord_bot:
    build:
      context: ./discord_bot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DISCORD_TOKEN=your_discord_token_here
    depends_on:
      - backend

volumes:
  db_data: